apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsyncpvc
  namespace: volsynctest
spec:
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: volsync-volsyncdemo-dst-20230131130615
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
