apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poddcdrpvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
