apiVersion: v1
kind: Service
metadata:
  name: httpd-service-rhel8vmodf
  namespace: virtualization
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt.io/domain: rhel8vmodf
    kubevirt.io/size: small
  sessionAffinity: None
  type: ClusterIP
